name: Test
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ayushma
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ayushma
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup Python 3.X
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip'
      - name: Cache Pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install CI dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/local.txt
      - name: Run Tests with coverage
        run: coverage run --parallel-mode --source='.' manage.py test
      - name: Generate coverage report
        run: |
          coverage combine
          coverage xml
          coverage report -m
